name: build windows
run-name: ${{ github.actor }} - build for windows

on:
    push: {}

    # push:
    #     branches:
    #         - '**'

jobs:
    build_windows:
        name: "build windows"
        runs-on: "windows-2022"
        # runs-on: "ubuntu-latest"
        needs: []
        if: always()
        strategy:
            matrix:
                arch: [x64]

        steps:
            - run: echo "Triggered by a ${{ github.event_name }} event."
            - run: echo "Running on ${{ runner.os }}"
            - run: echo "Checking out ${{ github.repository }}:${{ github.ref }}"

            - name: Check out repository
              uses: actions/checkout@v3
              with:
                lfs: true

            - name: Set up Python 3.10
              uses: actions/setup-python@v3
              with:
                python-version: "3.10"

            - name: Set up pyinstaller
              run: pip install pyinstaller setuptools wheel

            - name: Install dependencies
              run: pip install -r requirements.txt

            - name: Package application
              run: pyinstaller lufsplot.spec
            # - name: Package Application
            #   uses: JackMcKew/pyinstaller-action-windows@python3-10-pyinstaller-5-3
            #   with:
            #     path: .

            - name: get short hash
              run: echo "SHORT_SHA=$("${{ github.sha }}".SubString(0, 8))" >> $env:GITHUB_ENV

            - name: upload artifact
              uses: actions/upload-artifact@v2
              with:
                name: lufsplot-git${{ env.SHORT_SHA }}-win64.exe
                path: dist/lufsplot.exe

            - name: Release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              with:
                files: |
                    dist/lufsplot.exe
